CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    user_password TEXT NOT NULL,
    email TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    date_modified TIMESTAMP
);

ALTER TABLE user_babies
    ADD COLUMN
        user_id INTEGER REFERENCES users(id)
        ON DELETE SET NULL