CREATE TABLE user_babies (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    baby_name TEXT NOT NULL,
    about TEXT NOT NULL,
    image_url TEXT,
    total_score NUMERIC,
    total_votes NUMERIC,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);

ALTER TABLE users
    ADD COLUMN
        baby_id INTEGER REFERENCES user_babies(id)
        ON DELETE SET NULL

